# -*- coding: utf-8 -*-
"""SalaryPredictionML_Streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hzcTvuV36V0Dug5FkiiN2gszsThhJsyM
"""

!pip install streamlit
!pip install plotly

import streamlit as st
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.linear_model import LinearRegression
import numpy as np

st.title("Salary Predictor")
nav = st.sidebar.radio("Navigation", ["Home", "Prediction", "Contribute"])

